services:
  n8n:
    image: pratapshrey/leetcode-notes:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_LISTEN_ADDRESS=0.0.0.0
    volumes:
      - /home/anon/n8n-docker/.n8n/storage:/home/node/.n8n/storage
